# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-29 13:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveranciers',
            name='naam',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='netbeheerders',
            name='naam',
            field=models.CharField(max_length=15),
        ),
    ]
