# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-02 12:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0002_auto_20160229_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='kosten',
            name='datum',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
