# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-15 12:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0004_kosten_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leveranciers',
            name='id',
        ),
        migrations.AlterField(
            model_name='leveranciers',
            name='naam',
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
