# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-16 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bereken', '0005_auto_20160315_1341'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leveranciers',
            name='naam',
            field=models.CharField(max_length=35, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='netbeheerders',
            name='naam',
            field=models.CharField(max_length=35),
        ),
    ]
